### ISSUE TITLE
Cannot run symlink.. 

### ISSUE THREAD

**Issue by NSP-0123456** [zetamatta/nyagos#167]
On windows i have some symlink (mklink) that target executable file 
zpaq.exe -> zpaq64.exe 
on cmd if i call zpaq i get right pgm executed
on nyagos if i call zpaq or zpaq.exe  i got : 'zpaq.exe' is not recognized as an internal or external command....

**Comment by zetamatta** [comment]
Ok. I see the problem.

CMD.EXE could find zpaq64.exe as zpaq.exe, but nyagos.exe could not find.

**Comment by zetamatta** [comment]
### memo

- `os.exec.LookPath` could not find the executable symbolic linked.

**Comment by zetamatta** [comment]
I fixed the problem. Since `os.exec.LookPath` which seek executables cound not understand relative path on symbolic link, create my own `dos.LookPath`.

Would you confirm this executable runs as your expect.

* [nyagos-issue-167-amd64.zip](https://github.com/zetamatta/nyagos/files/518004/nyagos-issue-167-amd64.zip)
* [nyagos-issue-167-386.zip](https://github.com/zetamatta/nyagos/files/518005/nyagos-issue-167-386.zip)

**Comment by NSP-0123456** [comment]
I confirm that it is fixed... many thanks !
-- I also built and tested from the repository.
