### ISSUE TITLE
support: nyagos.eval + "context deadline exceeded"

### ISSUE THREAD

**Issue by malys** [zetamatta/nyagos#441]
I'm trying to interface nyagos to openai.
when I launch  nyagos.eval(cmd) => context deadline exceeded
It seems o be a timeout. The command succeed but slowly.

Do you know any workaround?

**Comment by hymkor** [comment]
` context deadline exceeded` is not the message that `nyagos.eval` outputs.
( There are no code setting timeout except for `ls` and completion )

On the commandline of nyagos :
```
lua_e "nyagos.eval('timeout 3600 >nul')"
```
→ It waits 3600 seconds and it does not show any error message.
`timeout` is `C:\Windows\System32\timeout.exe` .

**Comment by hymkor** [comment]
Ok. I understand. The completion of Nyagos has the mechanism to be stopped for timeout, because network filesystems are  sometimes so slow that users consider Nyagos hangs up. Because of same reason, `ls` has a timeout, too.

Other features do not have a timeout. One idea is to use `nyagos.key["C-I"]` (`C-I` means Control-I = TAB-Key)

```lua
nyagos.key["C-I"] = function(this)
    local text = string.sub(this.text,1,this.pos-1)
    text = text .. "(HOGEHOGE)"
    this:replacefrom(1,text)
    this:call("REPAINT_ON_NEWLINE")
end
```

`GGGGG` + TAB-Key → `GGGGG(HOGEHOGE)` and repaint all.
When you want to use the default function for completion, you can use `this:call("COMPLETE")` .
